#%RAML 1.0
title: Comparatory
description: API to identify similar companies
version: v1
baseUri: https://api.comparatory.io

/companies:
  /peers:
    description: Resource to identify similar companies
    get:
      description: "Get list of similar companies"
      queryParameters:
        company-name:
          displayName: "Company name or ticker"
          type: string
          description: "A company's business name or stock ticker"
          required: true
          example: "Delta Air Lines"
      responses:
        200:
          description: Company found, similar companies identified
          body:
            application/json:
              example: |
                {
                    "match": {
                        "id": "DAL",
                        "name": "Delta Air Lines, Inc. (DAL)"
                    },
                    "results": [
                        {
                            "id": "JBLU",
                            "name": "JetBlue Airways Corporation (JBLU)",
                            "rank": 1,
                            "sic_cd": "0000",
                            "sim_score": 0.85
                        },
                        {
                            "id": "ALK",
                            "name": "Alaska Air Group, Inc. (ALK)",
                            "rank": 2,
                            "sic_cd": "0000",
                            "sim_score": 0.83
                        },
                        {
                            "id": "ALGT",
                            "name": "Allegiant Travel Company (ALGT)",
                            "rank": 3,
                            "sic_cd": "0000",
                            "sim_score": 0.83
                        },
                        {
                            "id": "SAVE",
                            "name": "Spirit Airlines, Inc. (SAVE)",
                            "rank": 4,
                            "sic_cd": "0000",
                            "sim_score": 0.78
                        },
                        {
                            "id": "LUV",
                            "name": "Southwest Airlines Co. (LUV)",
                            "rank": 5,
                            "sic_cd": "0000",
                            "sim_score": 0.71
                        }
                    ]
                }
        400:
          description: Company not found
  /describe:
    description: Resource to identify companies matching a description
    get:
      description: "Get list of companies matching a description"
      queryParameters:
        description:
          displayName: "Company description"
          type: string
          description: "Description of a company's business operations"
          required: true
          example: "mobile phone manufacturer"
      responses:
        200:
          description: Matching companies identified
          body:
            application/json:
              example: |
                [
                    {
                        "id": "ABIL",
                        "name": "Ability Inc. (ABIL)",
                        "rank": 1,
                        "sim_score": 0.45824572
                    },
                    {
                        "id": "ATV",
                        "name": "Acorn International, Inc. (ATV)",
                        "rank": 2,
                        "sim_score": 0.31028354
                    },
                    {
                        "id": "CNTF",
                        "name": "China Techfaith Wireless Communication Technology Limited (CNTF)",
                        "rank": 3,
                        "sim_score": 0.2986524
                    },
                    {
                        "id": "STM",
                        "name": "STMicroelectronics N.V. (STM)",
                        "rank": 4,
                        "sim_score": 0.25856966
                    },
                    {
                        "id": "VOXX",
                        "name": "VOXX International Corporation (VOXX)",
                        "rank": 5,
                        "sim_score": 0.24855646
                    }
                ]
        400:
          description: No matching companies found

/plots:
  description: Resource for plotting companies
  get:
    description: Get plot points for 2d reduced embeddings
    responses:
      200:
        body:
          application/json:
            example: |
              [
                  {
                      "id": "NICK",
                      "name": "Nicholas Financial, Inc. (NICK)",
                      "sic_cd": "6153",
                      "x1": 10.03778997871596,
                      "x2": -7.20429410029356
                  },
                  {
                      "id": "MFIN",
                      "name": "Medallion Financial Corp. (MFIN)",
                      "sic_cd": "6199",
                      "x1": -3.2277884423503655,
                      "x2": 10.222132107613794
                  },
                  {
                      "id": "CLB",
                      "name": "Core Laboratories N.V. (CLB)",
                      "sic_cd": "1389",
                      "x1": 2.655370211307824,
                      "x2": 0.881550273090461
                  },
                  {
                      "id": "IMH",
                      "name": "Impac Mortgage Holdings, Inc. (IMH)",
                      "sic_cd": "6798",
                      "x1": 2.7931390871227206,
                      "x2": 4.00836380157074
                  },
                  {
                      "id": "BDR",
                      "name": "Blonder Tongue Laboratories, Inc. (BDR)",
                      "sic_cd": "3663",
                      "x1": 0.7598519737117487,
                      "x2": -0.3461153133448682
                  },
                  {
                      "id": "NVAX",
                      "name": "Novavax, Inc. (NVAX)",
                      "sic_cd": "2836",
                      "x1": -7.001517611339916,
                      "x2": 6.474902899599258
                  }
              ]