version: '2'

services:
 web:
   restart: always
   build: ./web
   container_name: app
   ports:
     - "8080:8000"
   volumes:
     - /comparatory/app/static
   env_file:
     - ./web/.docker-env

 nginx:
   restart: always
   build: ./nginx
   container_name: nginx
   ports:
     - "80:80"
   volumes:
     - /comparatory/app/static
   volumes_from:
     - web
   depends_on:
     - web
   links:
     - web:web
   environment:
    - VIRTUAL_PORT=8000